apiVersion: kubeadm.k8s.io/v1beta3
kind: ClusterConfiguration

clusterName: BLINDL
kubernetesVersion: v1.35.0

controlPlaneEndpoint: "192.168.56.10:6443"

networking:
  serviceSubnet: "10.96.0.0/12"
  podSubnet: "10.244.0.0/16"
  dnsDomain: "cluster.local"

apiServer:
  certSANs:
    - "192.168.56.10"

---
apiVersion: kubeadm.k8s.io/v1beta3
kind: InitConfiguration

nodeRegistration:
  criSocket: unix:///run/containerd/containerd.sock
  kubeletExtraArgs:
    cgroup-driver: systemd

---
apiVersion: kubelet.config.k8s.io/v1beta1
kind: KubeletConfiguration

cgroupDriver: systemd
