services:
  db:
    image: mysql:8.0
    container_name: mysql_backend
    restart: always
    environment:
      MYSQL_DATABASE: my_app_db
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_USER: dev_user
      MYSQL_PASSWORD: dev_password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  backend:
    build: .
    container_name: fastapi_backend
    volumes:
      - ./src:/app/src
      - /app/.venv
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=mysql+pymysql://root:root_password@db:3306/my_app_db
      - UV_PROJECT_ENVIRONMENT=/app/.venv 
    depends_on:
      - db

volumes:
  db_data: