all:
  children:
    master:
      hosts:
        k8s-master:
          ansible_host: 192.168.56.10
          ansible_user: vagrant
          ansible_ssh_private_key_file: ../.vagrant/machines/k8s-master/virtualbox/private_key
    worker:
      hosts:
        k8s-worker1:
          ansible_host: 192.168.56.11
          ansible_user: vagrant
          ansible_ssh_private_key_file: ../.vagrant/machines/k8s-worker1/virtualbox/private_key
        k8s-worker2:
          ansible_host: 192.168.56.12
          ansible_user: vagrant
          ansible_ssh_private_key_file: ../.vagrant/machines/k8s-worker2/virtualbox/private_key
